### ISSUE TITLE
Syncpipes still transfer items to vending machines when the pipe is disabled

### ISSUE THREAD

**Issue by AndrewMarkley** [Joe90384/syncPipes#2]
Put a storage chest and vending machine down.  Run pipe from chest to vending machine and upgrade it to get filter. Add an item to filter. Disabled the pipe. Place the item in the chest.  It still gets transferred over.  I've attached a screen capture of it.

https://user-images.githubusercontent.com/3367330/106305914-ebd5ce80-6222-11eb-82da-403c417886b9.mp4

**Comment by Joe90384** [comment]
Thanks for the detailed report. I've recreated it and am looking into the cause.

**Comment by Joe90384** [comment]
Fixed this. Just looking into the other issue you reported.

**Comment by AndrewMarkley** [comment]
Awesome! Thanks for fixing it so fast
