### ISSUE TITLE
Pipes to vending machines won't transfer multiple different items

### ISSUE THREAD

**Issue by AndrewMarkley** [Joe90384/syncPipes#3]
Put a storage chest and vending machine down.  Run pipe from chest to vending machine and upgrade it to get filter. Add 2+ items to filter. Place those items in the chest. Only 1 of the items will get moved to the vending machine and then it doesn't move the other one.

https://user-images.githubusercontent.com/3367330/106306649-f8a6f200-6223-11eb-9777-0b4538a2c281.mp4

**Comment by Joe90384** [comment]
Thanks for the detailed report. I've recreated it and am looking into the cause.

**Comment by Joe90384** [comment]
This appears to be an issue with Vending machine. If moving the items will clear the stack the move fails. I've put in a work around for the time being which should resolve this issue.
